// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID     int32
	PostID sql.NullInt32
	UserID sql.NullInt32
	Text   string
}

type Post struct {
	ID     int32
	UserID sql.NullInt32
	Title  string
	Text   string
}

type User struct {
	ID        int32
	Name      string
	LastName  string
	Email     string
	Age       int32
	CreatedAt time.Time
}
